name: build
run-name: ${{ github.actor }} is building the gradle project
on: [push]
jobs:
  build-main-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          java-version-file: ./.java-version
          distribution: temurin
          cache: gradle
      - run: ./gradlew build --no-daemon
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            build/test-results/test/*.xml
      - name: Spotbugs
        uses: github/codeql-action/upload-sarif@v2
        # The issues will be visible in the security tab in github
        with:
          # Path to SARIF file relative to the root of the repository or path to a folder with sarif files
          # wildcard doesnt work!
          sarif_file: build/reports/spotbugs
          # Optional category for the results
          # Used to differentiate multiple results for one commit
          category: Spotbugs
      - name: Sonarlint
        uses: github/codeql-action/upload-sarif@v2
        # The issues will be visible in the security tab in github
        with:
          # Path to SARIF file relative to the root of the repository or path to a folder with sarif files
          # wildcard doesnt work!
          sarif_file: build/reports/sonarlint
          # Optional category for the results
          # Used to differentiate multiple results for one commit
          category: Sonarlint
      - name: Archive main artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs
      - name: Archive code quality reports
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: |
            build/reports/*/*.sarif
